export const quotes = [
  "🌱 « La meilleure énergie est celle qu’on ne consomme pas. »",
  "💡 « L’IA peut être verte si on la pense ainsi. »",
  "🌍 « Moins de data, plus d’impact. »",
  "♻️ « Recycler ses données, c’est aussi penser écologie. »",
  "🧠 « Une IA responsable commence par un humain responsable. »",
  "🌬️ « L’empreinte carbone de l’IA n’est pas virtuelle. »",
  "🔋 « Optimiser les modèles, c’est économiser l’énergie. »",
  "🚲 « Et si on ralentissait l’IA ? »",
  "📉 « L’efficacité énergétique est une révolution silencieuse. »",
  "🔍 « L’IA ne remplace pas la sobriété. »",
  "🕊️ « Moins d’algorithmes, plus de sens. »",
  "🌳 « L’intelligence est aussi écologique. »",
  "⚡ « Chaque paramètre a un coût énergétique. »",
  "🧩 « La tech verte n’existe pas sans remise en question. »",
  "🌡️ « L’IA consomme, comme nous tous. »",
  "💬 « Parler d’IA, c’est parler d’énergie. »",
  "🛰️ « Des données, mais à quel prix ? »",
  "🌖 « Plus de calcul, moins de nature. »",
  "💻 « Tous les modèles ne sont pas durables. »",
  "📱 « Ton smartphone entraîne peut-être une IA. »",
  "🏭 « L’IA dépend des serveurs, pas de magie. »",
  "🧯 « Réduire, c’est innover. »",
  "🌐 « L’empreinte carbone du cloud est bien réelle. »",
  "🏕️ « Le numérique aussi peut ralentir. »",
  "🔧 « Sobriété n’est pas régression. »",
  "🌈 « L’IA éthique est aussi écologique. »",
  "🌎 « Aucune intelligence sans planète. »",
  "🛑 « Une IA inutile est une IA polluante. »",
  "📦 « Moins d’infos, plus d’actions. »",
  "🔄 « Repenser, c’est déjà agir. »"
];